env:
  global:
    - CI_HOME=`pwd`
language: python
python:
 - "2.7"
before_install:
  - gem install package_cloud
script:
  - bash env.sh
  - sudo -E sh -c "bash init.sh"
  - sudo -E sh -c "bash build.sh"
  - bash push.sh
